name: Update Feed Posts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'

jobs:
  parse-feeds:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Parse feed posts
        uses: xaoxuu/feed-posts-parser@0107be40bed6ec4924d5e541ccce935dfbaa1507
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          posts_count: 3

  generate:
    needs: parse-feeds
    permissions:
      contents: write
      issues: read
    uses: ./.github/workflows/generate-data.yml
