name: Check Reachability

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  check-links:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@e8d4307400f9427dba7cb98e488d6ab85f1cec5f # v4

      - name: Check site reachability
        run: python scripts/check_reachability.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  generate:
    needs: check-links
    permissions:
      contents: write
      issues: read
    uses: ./.github/workflows/generate-data.yml
