name: Check Reachability

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  check-links:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Check site reachability
        uses: xaoxuu/links-checker@c892d42fe441593786947757b9d5fdfa09aa239f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          checker: reachability
          unreachable_label: 失联
          exclude_issue_with_labels: 审核中, 白名单

  generate:
    needs: check-links
    permissions:
      contents: write
      issues: read
    uses: ./.github/workflows/generate-data.yml
